from . import sisb_hr_attendance
from . import utility
from . import work_schedule
from . import wizard
from . import boarding_list
from . import hr_recruitment
from . import hr_resign
from . import hr
from . import sisb_hr_employee
from . import sisb_allocation_leave
from . import sisb_hr_holidays
from . import analysis_employee_report
from . import academic_week
from . import res_config
from . import res_partner
from . import sisb_account
from . import sisb_hr
from . import sisb_res_users
from . import report
from . import hr_schedule
