{
    "name" : "SISB Human Resources",
    "version" : "1.0",
    "author" : "Tigernix, Pte Ltd",
    "website" : "http://www.tigernix.com",
    "category": "Human Resources/Attendance/Leaves",
    "summary": "",
    "description": """ SISB Human Resources Management. """,
    "depends": [
        'base',
        'hr',
        'hr_attendance',
        'hr_holidays',
        'hr_holidays_request',
        'sisb_project',
        'sisb_purchase',
        'lma_sisb',
        'pathlight_sisb',
        'mail',
    ],
    "data" : [ 
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/probation_completion_report_view.xml',
        'report/default_report_header.xml',
        'report/attendance_summary_report_view.xml',
        'report/summary_attendance_view.xml',
        'report/detail_summary_attendance_view.xml',
        'report/emp_individual_detail_attendance_template_view.xml',
        'report/employee_absent_report_template_view.xml',
        'report/individual_overtime_detail_template_view.xml',
        'report/summary_overtime_report_view.xml',
        'report/overtime_work_inspection_report_view.xml',
        'report/leave_report/leave_summary_report_template_view.xml',
        'report/leave_report/leave_accumulative_report_template_view.xml',
        'report/personnel_transfer_notification_form_view.xml',
        'report/staff_tf_checklist_view.xml',
        'report/employee_movement_report_view.xml',
        'report/years_of_service_report_template_view.xml',
        'report/employee_timesheet_report_view.xml',
        'report/lateness_early_checkout_report_view.xml',
        'views/hr_attendance.xml',
        'views/report_view.xml',
        'views/sisb_hr_view.xml',
        'wizard/emp_import_schedule_view.xml',
        'wizard/export_sched_template_view.xml',
        'wizard/emp_change_shift_view.xml',
        'wizard/emp_quick_act_deact_view.xml',
        'wizard/wizard_confirmation_transfer_view.xml',
        'wizard/lateness_early_wiz.xml',
        'work_schedule_view.xml',
        'boarding_list_view.xml',
        'hr_recruitment_view.xml',
        'hr_resign_view.xml',
        'hr_view.xml',
        'sisb_account_view.xml',
        'academic_week_view.xml',
        'sisb_res_users_view.xml',
        'edi/sisb_hr_email_template.xml',
        'edi/leave_req_email_template.xml',
        'edi/sisb_hr_applicant_notif_template.xml',
        'edi/boarding_list_request.xml',
        'edi/sisb_exit_interview_survey.xml',
        'data/sisb_hr_custom_data.xml',
        'data/hr_sequence.xml',
        'sisb_hr_attendance_view.xml',
        'analysis_employee_report_view.xml',
        'sisb_hr_employee_view.xml',
        'sisb_hr_holidays_view.xml',
        'hr_schedule_view.xml',
        'wizard/attendance_summary_view.xml',
        'wizard/wizard_summary_report_view.xml',
        'wizard/wizard_detail_attendance_view.xml',
        'wizard/wizard_emp_attendance_detail_view.xml',
        'wizard/wizard_employee_absent_view.xml',
        'wizard/leave_summary_wiz_view.xml',
        'wizard/leave_accumulative_wiz_view.xml',
        'wizard/employee_overtime_detailed_view.xml',
        'wizard/leave_early_wiz_view.xml',
        'wizard/summary_overtime_wiz_view.xml',
        'wizard/overtime_work_inspection_wiz_view.xml',
        'wizard/attendance_summary_excel_wiz_view.xml',
        'wizard/employee_movement_wizard_view.xml',
        'wizard/years_of_service_view.xml',
        'wizard/sisb_hr_wizard_view.xml',
        
    ],
    "demo": [],
    "css": [],
    "qweb": [
        'static/src/xml/attendance.xml'
    ],
    "external_dependencies": {
    },
    "installable": True,
    "auto_install": False,
    "application": True,
}
